version: 2
formats:
  - htmlzip
  - pdf
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/environment-docs.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
