version: 2
formats:
  - htmlzip
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/environment-docs.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: True
