FROM mambaorg/micromamba:0.15.2

ADD . /msibi

WORKDIR /msibi

RUN micromamba install -y -n base -f environment.yml && \
    micromamba clean --all --yes && \
    python setup.py install

WORKDIR /home
