FROM cmelab/gpuhoomdconda:latest

ADD . /msibi

WORKDIR /msibi

# Install in base environment
RUN conda env update -n base -f environment-nohoomd.yml && \
    conda clean --all --yes -f  &&\
    python setup.py install

WORKDIR /home
